import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";

import "./globals.css";
import Providers from "./providers";

// const inter = Inter({ subsets: ["latin"] });

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mark Slorach",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={lato.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
